on:
  pull_request:
    types: [opened]
    branches:
      - test/*

jobs:
  createFile:
    name: Create Version File
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: 1arp/create-a-file-action@0.2
        with:
          path: '/'
          file: 'VERSION'
          content: ${{ github.head_ref }}
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: stage changed file
        run: git add .
      - name: commit version file
        run: git commit -m "update version"
      - name: push code
        run: git push