on:
  pull_request:
    types: [opened]
    branches:
      - test/*

jobs:
  createFile:
    name: Create Version File
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 1arp/create-a-file-action@0.2
        with:
          path: '/'
          file: 'VERSION'
          content: ${GITHUB_REF#refs/heads/}
      - name: stage changed file
        run: git add .
      - name: commit version file
        run: git commit -m "update version"
      - name: push code
        run: git push